const express = require('express')
const router = express.Router()

const userRouter = require('./UserController')
const mandorRouter = require('./MandorController')
const vendorRouter = require('./VendorController')
const projectRouter = require('./ProjectController')
const jasaRouter = require('./JasaController')
const cartRouter = require('./CartController')
const blogRouter = require('./BlogController')
const paymentRouter = require('./PaymentController')
const authRouter = require('./Auth')
const negoRouter = require('./NegoController')
const portofolioRouter = require('./PortofolioController')
const reviewRouter = require('./ReviewController')

router.use('/user', userRouter)
router.use('/mandor', mandorRouter)
router.use('/vendor',vendorRouter)
router.use('/auth', authRouter)
router.use('/project', projectRouter)
router.use('/blog', blogRouter)
router.use('/jasa', jasaRouter)
router.use('/cart', cartRouter)
router.use('/payment', paymentRouter)
router.use('/nego', negoRouter)
router.use('/portofolio',portofolioRouter)
router.use('/review',reviewRouter)

module.exports = router